---
- name: "Disable Common services "
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  with_items: "{{ windows_tune_common_svc }}"

- name: "Determine if Core or Desktop Experience"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    name: InstallationType
  register: os_version

- name: "Disable Core experience services "
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  with_items: "{{ windows_tune_core_svc }}"
  when: os_version.value == "Server"
