---
- name: Set proxy tasks
  ansible.builtin.include_tasks: proxy.yml
  when: windows_tune_run_proxy

- name: Customize tasks
  ansible.builtin.include_tasks: customize.yml
  when: windows_tune_run_customize

- name: Disable services tasks
  ansible.builtin.include_tasks: disable_services.yml
  when: windows_tune_run_disable_services

- name: Disable ipv6 tasks
  ansible.builtin.include_tasks: disable_ipv6.yml
  when: windows_tune_run_disable_ipv6

- name: Upgrade tasks
  ansible.builtin.include_tasks: upgrade.yml
  when: windows_tune_run_upgrade

- name: Cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml
  when: windows_tune_run_cleanup
