---
- name: "Configure IE proxy settings to apply to all users"
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxySettingsPerUser
    data: 0
    type: dword
    state: present
  retries: 30
  delay: 30

- name: "Configure IE to use explicit proxy host with port and without auto detection"
  community.windows.win_inet_proxy:
    auto_detect: false
    proxy: "{{ windows_tune_proxy }}"
